apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-orders-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-orders
  template:
    metadata:
      labels:
        app: flask-orders
    spec:
      containers:
      - name: flask-orders
        image: dvirbf/flask-orders:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"